name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  
  schedule:
    - cron: '00 10 * * *'  # At 17:00 every day.  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Lighthouse
        run: |
          npm install -g @unlighthouse/cli puppeteer
          npm install
          npm test

      - name: Commit results
        run: |
          git config --global user.name scott-skyward
          git config --global user.email sdavis@skywarditsolutions.com
          git add .
          git commit -m "Lighthouse audit data"
          git push
