name: Mobile
on:
  workflow_dispatch:  
  #schedule:
  #  - cron: '00 08 * * *'  # At 08:00 UTC every day. (2am Denver time) 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Lighthouse
        run: |
          npm install -g @unlighthouse/cli puppeteer
          npm install
          npm run testm
          npm run summary

      - name: Commit results
        run: |
          git config --global user.name scott-skyward
          git config --global user.email sdavis@skywarditsolutions.com
          git add .
          git commit -m "Mobile Lighthouse audit data"
          git push
